### ISSUE TITLE
Stemming returns empty result at certain words

### ISSUE THREAD

**Issue by PuruVJ** [oramasearch/orama#440] opened 2023-07-07 17:27 UTC
**Describe the bug**

I am integrating Orama into Svelte.dev's search, with stemming turned on. We have a page called "Migration". When I type "migrat", I get perfect results. But the second it's "migrati" or "migration", it breaks down and gives me 0 results. Once its "migration", it works. And it only happens when **STEMMING** is on. Check the video below:

https://github.com/oramasearch/orama/assets/47742487/a077b60f-a23b-4899-b736-44fec0811127

**To Reproduce**
1. Go to https://stackblitz.com/edit/stackblitz-starters-m9rjt7?file=content.json,index.mjs
2. In terminal, type node index.js "migrat". Then replace with "migrati" to see the empty array.
3. Set `stemming: false` and try these queries again, this bug doesn't happen

**Expected behavior**
Results should keep showing even if query is "migrati" or "migratio" when stemming is on

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Arc(Chromium)
 - Version [e.g. 22] Chromium version 114

**Additional context**

**Comment by micheleriva** [comment] 2023-07-10 08:19
Hi @PuruVJ,
This is an expected behavior, but let me explain.

We documented it [in this blog post](https://oramasearch.com/blog/should-i-stem-or-should-i-go), where we describe how stemming might not be helpful for instant search experiences.

The reason is relatively easy to explain: we only keep stemmed words in our indexes to avoid large duplications by maintaining both stemmed and non-stemmed forms of every token.

Right now, when stemming is enabled, Orama reasons the following way

```
tokens -> tokenize -> apply stemming to individual tokens -> save stemmed tokens to index
```

So as you can see we discard the original tokens to avoid the pain of having a large index to be either kept in memory on the browser or downloaded at page load time.

So when is stemming actually useful? If you're not using typeahead/instant search, you can rely on stemming as it will bring you to a new page with your search results and won't display stuff as-you-type.

Let me know if that's a deal breaker for you; I personally believe documentation websites don't need stemming, but if you believe this is needed on Svelte Kit docs, we can prioritize a solution for you.

**Comment by micheleriva** [comment] 2023-07-18 13:48
Hi @PuruVJ is there anything we can do before closing this?

**Closed** 2023-08-16 13:18 UTC
