### ISSUE TITLE
Suggestion: add other JS libraries to the benchmark, like Flexsearch

### ISSUE THREAD

**Issue by paulocoghi** [oramasearch/orama#76] opened 2022-08-02 21:44 UTC
**Is your feature request related to a problem? Please describe.**
It would be better if we could compare how lyra behaves among other existing full-text search JS libraries.

**Describe the solution you'd like**
I propose to add the main existing libraries to the benchmark, to more easily compare the benefits of lyra.

**Comment by micheleriva** [comment] 2022-08-03 08:06
Hi @paulocoghi ,
yes, it would be interesting to see a direct comparison with other libraries. We already have a `packages/benchmarks` directory with some datasets, we'd be glad if anyone could open a PR to support this

**Comment by Zombobot1** [comment] 2022-12-15 00:45
I tried to use the lyra in the following way: from several consecutive words, find the page of the book from which they were taken. I used "Harry Potter book 5" and divided it into pages of 2000 words each. I then did a search with the `exact` option. The results were poor because I assume that lyra does not take into account the proximity of words within a page, so there is no difference between two words that go in sequence or are separated by other paragraphs. I decided to explore other libraries and found `Flexsearch`. It has a scoring [benchmark](https://nextapps-de.github.io/flexsearch/bench/match.html) for a similar use case (Indexed Text: "Gulliver's Travels" (Swift Jonathan 1726)):

![image](https://user-images.githubusercontent.com/48030070/207743859-d0e09767-6a2d-4ba0-96f8-8b97d6afca5d.png)

As you can see, lyra's results don't look promising.

I suggest adding a "Scoring" page to the "Text analysis" section of the documentation site to help people understand how to improve it. For example, when I divided the pages into paragraphs, queried lyra, and combined the results, I was able to meet my requirements.

There is another interesting benchmark from flexsearch:

![image](https://user-images.githubusercontent.com/48030070/207744716-3255d874-0d17-4330-a9c2-22a6e74c426a.png)

I didn't expect to see that lyra's performance drops so quickly for long queries.

I really want lyra to become the main search engine for javascript, so I think if you describe how scoring works, it might help other people choose lyra over flexsearch or other libraries.

**Comment by leeoniya** [comment] 2022-12-15 00:50
another biased benchmark: https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work

**Comment by abhay187** [comment] 2022-12-19 17:47
@Zombobot1 thanks. These benchmarks are eye-openers. We need a strong reply from the core team. Till then I am staying away from this.

**Comment by abhay187** [comment] 2022-12-19 17:48
@micheleriva any response why Lyra performed poorly on benchmarks?

**Comment by micheleriva** [comment] 2022-12-19 19:30
@abhay187 I have opinions, but I want to demonstrate them with numbers. Unfortunately, right now I am not in a position where I have numbers to share, I am working on it.

**Comment by abhay187** [comment] 2022-12-19 19:47
Hey @micheleriva good luck mate. Excited to see the results. 
Also, I have started testing Lyra but the hit is always empty. Can you check if I am doing anything wrong?
```
import { create, insertBatch, search } from '@lyrasearch/lyra'

const db = create({
	schema: {
		word: 'string'
	}
})

const addData = async () => {
	const docs = [
		'Indian Institute of Technology (BHU) Varanasi',
		'Indian Institute of Technology Bhilai',
		'Indian Institute Of Technology Bhubaneswar',
		'Indian Institute of Technology Bombay',
		'Indian Institute of Technology Delhi',
		'Indian Institute Of Technology Dharwad',
		'Indian Institute of Technology Guwahati',
		'Indian Institute of Technology Jodhpur',
		'Indian Institute of Technology Kanpur',
		'Indian Institute of Technology Kharagpur'
	]

	await insertBatch(db, docs)
}

const searchFn = () => {
	const searchResult = search(db, {
		term: 'Indian',
		properties: '*'
	})

	console.log(searchResult)
}

export const setupSearch = (element) => {
	element.addEventListener('click', () => {
		searchFn()
	})
}

addData()
```
I am using vite+vanilla js template

https://user-images.githubusercontent.com/61496865/208507621-e1742dca-8bf6-4f68-a866-f81e4013b32f.mov

**Comment by micheleriva** [comment] 2022-12-19 19:49
@abhay187 would you mind opening a separate issue for this? And a reproducible repo/sandbox would be excellent. Thanks!

**Comment by abhay187** [comment] 2022-12-19 19:50
> @abhay187 would you mind opening a separate issue for this? And a reproducible repo/sandbox would be excellent. Thanks!

Sure

**Comment by micheleriva** [comment] 2023-06-30 13:34
Closing as a lot of things changed and this issue is not relevant anymore

**Closed by micheleriva** 2023-06-30 13:34 UTC
Labels: discussion
